# Generated by Django 5.1.5 on 2025-01-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_posts', to='core.post'),
        ),
    ]
