# Generated by Django 5.1.5 on 2025-01-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_followerscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='followersCount',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='core.profile'),
        ),
    ]
