# Generated by Django 5.1.5 on 2025-01-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_followerscount_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
